changed valid values for  the sex variable
nf-core/raredisease pull request #550
Opened 2024-05-16 08:30 UTC by sima-r

This is now compatible with the PED file format and documentation. 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-05-16 08:45 UTC, sima-r commented
@ramprasadn I wasn't sure about the base branch for this PR. Just let me know if this patch branch is not the best choice :D

2024-05-18 13:51 UTC, ramprasadn commented
Hi @sima-r! I have changed the base from patch to dev since these changes will be going into a minor release. As for the lint error, it was related changes in the recent template merge. It has been addressed in the dev branch so a merge with the current dev should fix it.

2024-05-18 14:05 UTC, ramprasadn requested changes
@sima-r Could you update the CHANGELOG.md file?

2024-05-20 09:31 UTC, ramprasadn approved these changes

2024-05-20 09:45 UTC, merged